### PR TITLE
Correcting the github account link for Nitika

### PR DESCRIPTION
**Pull request by nitikagarw**

### CODE REVIEW

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
LIST.md file changes don't get rendered. Please remove the changes from LIST.md.

**Comment by nitikagarw** [comment]
@tapaswenipathak  Shouldn't the file be removed if it's not used? 
I think we should have consistent changes. If we have different urls in different files, this might create confusion.

**Comment by tapaswenipathak** [comment]
@nitikagarw: It is the base for all listed people you see in https://women-on-github.herokuapp.com/. Scheduler isn't automated, filed a ticket - https://github.com/tapaswenipathak/Women-GitHubers/issues/143. After the ticket is closed list.md changes can be replaced w/ readme.md.

**Comment by nitikagarw** [comment]
Thanks, updated the PR.

**Pull request merged**
