### PR TITLE
Enable ci

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by thefourtheye** [comment]
@tapasweni-pathak Did you get a chance to take a look at this?

**Comment by tapaswenipathak** [comment]
Thanks for this @thefourtheye. :+1:

**Comment by thefourtheye** [comment]
@tapasweni-pathak you are welcome :) Planning to merge?

**Comment by tapaswenipathak** [comment]
Still need to test things. I'm not able to find time, will try to do it soon. Thanks for the patience. :)

**Comment by tapaswenipathak** [comment]
@thefourtheye You closed it? Should I use this code and give you the credit?

**Pull request closed without merging**
