### PR TITLE
#149 - integrated travis to check for dead links

### LINKED ISSUE #149: Remove non-active profiles
Some of the profiles in the list are 404 links.
A script in travis (https://travis-ci.org/) using https://github.com/dkhamsing/awesome_bot can be used to check for 404 links.
I can work on this.

### PR DESCRIPTION
**Pull request by Swati4star**
Just need to add .travis.yml file
Can you integrate travis to your repo? and then, this all will be in place for your repo.
Fixes #149 

The awesome_bot gave a list of inactive profiles:
https://travis-ci.org/Swati4star/Women-GitHubers/builds/593913629

### CODE REVIEW

**Comment by Swati4star** [comment]
The fixed build, with dead links removed:
https://travis-ci.org/Swati4star/Women-GitHubers/builds/593916239

**Review by tapaswenipathak — COMMENTED** [review]
Good item. Please write the label chore PR from now.

**Comment by Swati4star** [comment]
@tapaswenipathak Did you enabled travis for this repo? I can then add the link to travis build status in your readme.

**Comment by tapaswenipathak** [comment]
On Sun, Oct 6, 2019 at 10:49 PM Swati Garg <notifications@github.com> wrote:
>
> @tapaswenipathak Did you enabled travis for this repository? I can add the link of travis build status in your readme.

Sure, just did.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Pull request merged**
