### PR TITLE
Web app and scheduler

### PR DESCRIPTION
**Pull request by PrabhanshuAttri**
We have developed a web app which shows this list in an user friendly manner which might attract more people and developers to this project. Here is the link to the web app: https://women-on-github.herokuapp.com/

You can access the sorted list from this link: http://women-on-github.herokuapp.com/sorted.php

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@PrabhanshuAttri @fatimarafiqui This is so cool! Thanks for the work. :+1: :smile: 

I'll review and merge. Can you please add a license? Take the MIT license, write your names and year and push it to this PR.

**Comment by PrabhanshuAttri** [comment]
@tapasweni-pathak Glad you liked it. It's under MIT License only (footer on the web page). We forgot to add the file. :stuck_out_tongue:  We have some ideas to further refine the Women on Github initiative. This will improve the future prospects if the same.

LICENCE added

**Comment by tapaswenipathak** [comment]
@PrabhanshuAttri It got some conflicts. :( 
Can you please resolve them?

**Comment by tapaswenipathak** [comment]
@fatimarafiqui @PrabhanshuAttri I have some questions. I don't have enough time to look into the code. Great if any one of you can answer.
1. Are you using GitHub API to fetch each user's information? For ex : The name, picture, company e.t.c, [here](https://gyazo.com/de72436f2b61ba814b5df22b593ecdff).
2. Have you hardcoded the list somewhere, or you are picking it up from the repository and scheduling the pick? If yes, how long is the break?

Can you link the blog post somewhere on the website? Then I will be able to add this as website on the GitHub repository.

**Pull request closed without merging**
