### PR TITLE
Fixed styling issue of view on github button

### PR DESCRIPTION
**Pull request by codingonHP**
Currently:
image

Now (after small fix)
image

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
Thank you. 

Merging this will not publish the changes on herokuapp. @fatimarafiqui, @PrabhanshuAttri Can you please push the change to herokuapp or give me the push privilege?

**Comment by codingonHP** [comment]
@tapasweni-pathak : You are welcome :)
Do you mind me enhancing the look and feel of the overall website ? Also if you can update the repo with how to setup project locally information, it would help someone with zero knowledge of PHP.

**Comment by PrabhanshuAttri** [comment]
@tapasweni-pathak done.
@codingonHP we are working on a new website with some more features. I will be available in[ this repo](https://github.com/forksociety/githubble) very soon.

**Comment by codingonHP** [comment]
@PrabhanshuAttri Cool :+1:

**Pull request merged**
