### PR TITLE
Inspire Me App

### LINKED ISSUE #136: Create an Android app - Inspire me
Create an Android app and show one woman on phone screen and their GitHub/open source achievements in a day, the button should say `Inspire me!` 

cc @Siddharth1698.

### PR DESCRIPTION
**Pull request by Siddharth1698**
Fix https://github.com/tapaswenipathak/Women-GitHubers/issues/136.

- [x] Add instructions
- [x] Add screenshots

Created an android app Inspire Me
-Starts with a screen with text called "INSPIRE ME"
-On clicking on the text a women-githuber pic and details and link having the github account is generated.

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Please add screenshots or instructions on how can I run the app. Can you publish the app?

**Comment by Siddharth1698** [comment]
Alright ill add screenshots too...
I can send you the apk file link. I dont have a personal google play publishing account yet

**Comment by Siddharth1698** [comment]
Have added screenshot , json file, link to download app and instructions to run using normal android files

**Comment by Siddharth1698** [comment]
i have just created this app as basic requirement , if you need ill start to develop it even more especially with features and designs . :)

**Comment by tapaswenipathak** [comment]
For internship the intern would work on creating app using React.
Thanks for the work, looks great!

On Sat, May 11, 2019 at 11:10 PM Siddharth M <notifications@github.com> wrote:
>
> i have just created this app as basic requirement , if you need ill start to develop it even more especially with features and designs . :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by pdurbin** [comment]
@Siddharth1698 maybe you could put the Inspire Me app in F-Droid: https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included

**Comment by Siddharth1698** [comment]
Alright

**Pull request merged**
