### PR TITLE
Updating with few more names.

### PR DESCRIPTION
**Pull request by sara-02**

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@sara-02 Some names were already there. If I merge your PR, that will lead to duplication of names. Can you please look into it and fix it?

**Comment by sara-02** [comment]
Apart from Carol's name I could not find other duplications, updated that.

**Comment by tapaswenipathak** [comment]
@sara-02 I can't see the changes in this PR? :(

**Comment by sara-02** [comment]
Made the changes, had removed the name from the wrong place.

**Pull request closed without merging**
