### PR TITLE
Added two more developers

### PR DESCRIPTION
**Pull request by ankitashukla**

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@ankitashukla Thanks for this. It has some conflicts can you correct them?

**Comment by ankitashukla** [comment]
@tapasweni-pathak Resolved! :)

**Comment by tapaswenipathak** [comment]
@ankitashukla This seems to be a mess now. Can you please rebase?

**Comment by tapaswenipathak** [comment]
Please reopen if updated or create a new one.

**Pull request closed without merging**
